export const GET_ARTICLES_LIST_REQUEST = "GET_ARTICLES_LIST";
export const GET_ARTICLES_LIST_SUCCESS = "GET_ARTICLES_LIST_SUCCESS";
export const GET_ARTICLES_LIST_FAILED = "GET_ARTICLES_LIST_FAILED";
