
export const POST_AQUARIUM_FORM_DATA = "POST_AQUARIUM_FORM_DATA";
export const POST_CONTACTUS_FORM = "POST_CONTACTUS_FORM";
export const POST_PET_RELOCATION = "POST_PET_RELOCATION";
export const AQU_RESPONSE = "AQU_RESPONSE";
export const CONTACT_RESPONSE = "CONTACT_RESPONSE";
export const PET_REL_RESPONSE = "PET_REL_RESPONSE";

