// Get Stores List

export const GET_STORES_LIST_REQUEST = "GET_STORES_LIST";
export const GET_STORES_LIST_SUCCESS = "GET_STORES_LIST_SUCCESS";
export const GET_STORES_LIST_FAILED = "GET_STORES_LIST_FAILED";

// Get store details by storeId

export const GET_STORE_DETAILS_REQUEST = "GET_STORE_DETAILS";
export const GET_STORE_DETAILS_SUCCESS = "GET_STORE_DETAILS_SUCCESS";
export const GET_STORE_DETAILS_FAILED = "GET_STORE_DETAILS_FAILED";